# Generated by Django 4.1.6 on 2023-03-30 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='дата')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='количество правильных ответов')),
                ('consecutive_days', models.PositiveIntegerField(default=0, verbose_name='количество последовательных дней')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'статистика пользователя',
                'verbose_name_plural': 'статистика пользователей',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
