# Generated by Django 4.1.6 on 2023-03-30 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonstats',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='дата'),
        ),
    ]
