# Generated by Django 4.2.4 on 2023-08-03 07:11

import cards.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_text', models.TextField(verbose_name='текст на передней стороне')),
                ('back_text', models.TextField(verbose_name='текст на задней стороне')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='дата изменения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'карточка',
                'verbose_name_plural': 'карточки',
            },
        ),
        migrations.CreateModel(
            name='CardImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_image', models.ImageField(blank=True, null=True, upload_to=cards.models._get_card_front_image_filepath, verbose_name='изображение на передней стороне')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to=cards.models._get_card_back_image_filepath, verbose_name='изображение на задней стороне')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card', verbose_name='карточка')),
            ],
            options={
                'verbose_name': 'изображения карточки',
                'verbose_name_plural': 'изображения карточек',
            },
        ),
    ]
