# Generated by Django 4.1.6 on 2023-02-15 10:25

import cards.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_image', models.ImageField(upload_to=cards.models._get_card_front_image_filepath, verbose_name='изображение на передней стороне')),
                ('back_image', models.ImageField(upload_to=cards.models._get_card_back_image_filepath, verbose_name='изображение на задней стороне')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card', verbose_name='карточка')),
            ],
            options={
                'verbose_name': 'изображения карточки',
                'verbose_name_plural': 'изображения карточек',
            },
        ),
    ]
