# Generated by Django 4.1.6 on 2023-03-30 09:19

import cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_cardimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardimages',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to=cards.models._get_card_back_image_filepath, verbose_name='изображение на задней стороне'),
        ),
        migrations.AlterField(
            model_name='cardimages',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to=cards.models._get_card_front_image_filepath, verbose_name='изображение на передней стороне'),
        ),
    ]
